## Feature Encoding 
Feature encoding is the process of transforming categorical features into numeric features. This is necessary because machine learning algorithms can only handle numeric features. There are many different ways to encode categorical features, and each method has its own advantages and disadvantages. In this notebook, we will explore some of the most popular methods for encoding categorical features, such as:

.Label encoding
.Ordinal encoding
.One-hot encoding
.Binary encoding

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

# load the data set 
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [4]:
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [5]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [6]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (1.3.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.26.0)
Requirement already satisfied: scipy>=1.5.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.2.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
# let's encode the time in labelencoder with sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
le = LabelEncoder()
df['encoded_time'] = le.fit_transform(df['time'])
df.head(15)

    total_bill   tip     sex smoker  day    time  size  encoded_time
0        16.99  1.01  Female     No  Sun  Dinner     2             0
1        10.34  1.66    Male     No  Sun  Dinner     3             0
2        21.01  3.50    Male     No  Sun  Dinner     3             0
3        23.68  3.31    Male     No  Sun  Dinner     2             0
4        24.59  3.61  Female     No  Sun  Dinner     4             0
5        25.29  4.71    Male     No  Sun  Dinner     4             0
6         8.77  2.00    Male     No  Sun  Dinner     2             0
7        26.88  3.12    Male     No  Sun  Dinner     4             0
8        15.04  1.96    Male     No  Sun  Dinner     2             0
9        14.78  3.23    Male     No  Sun  Dinner     2             0
10       10.27  1.71    Male     No  Sun  Dinner     2             0
11       35.26  5.00  Female     No  Sun  Dinner     4             0
12       15.42  1.57    Male     No  Sun  Dinner     2             0
13       18.43  3.00    Male     No  Sun  Dinner     4             0
14       14.83  3.02  Female     No  Sun  Dinner     2             0

In [8]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [9]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [10]:
df['encoded_time'].value_counts()

encoded_time
0    176
1     68
Name: count, dtype: int64

In [11]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [14]:
df['encoded_day'] = le.fit_transform(df['day'])
df['encoded_day']

0      2
1      2
2      2
3      2
4      2
      ..
239    1
240    1
241    1
242    1
243    3
Name: encoded_day, Length: 244, dtype: int32

In [12]:
# ordinal encoding the day column using specific order
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
df['encoded_day'] = oe.fit_transform(df[['day']])
df.head()

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,3.0

In [15]:
# # one hot encoding on day column
ohe = OneHotEncoder()
ohe.fit_transform(df[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [16]:
# example of one hot encoding
titanic = sns.load_dataset('titanic')

onehot_encoder = OneHotEncoder(sparse=False)
embarked_onehot = onehot_encoder.fit_transform(titanic[['embarked']])
embarked_onehot_df = pd.DataFrame(embarked_onehot, columns=onehot_encoder.get_feature_names_out(['embarked']))
titanic = pd.concat([titanic.reset_index(drop=True), embarked_onehot_df.reset_index(drop=True)], axis=1)
titanic.head()

c:\Users\ghg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0

In [18]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
                                              0.0/81.9 kB ? eta -:--:--
     -----                                    10.2/81.9 kB ? eta -:--:--
     -----                                    10.2/81.9 kB ? eta -:--:--
     -----                                    10.2/81.9 kB ? eta -:--:--
     --------------                         30.7/81.9 kB 163.8 kB/s eta 0:00:01
     -------------------                    41.0/81.9 kB 151.3 kB/s eta 0:00:01
     ----------------------------           61.4/81.9 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 81.9/81.9 kB 254.9 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in c:\users\ghg\miniconda3\lib\site-packages (from category_encoders) (1.26.1)
Collecting scikit-learn>=0.20.0 (from category_encoders)
  Using cached scikit_learn-1.3.2-cp311-cp311-win_amd64.whl (9.2 MB)
Requirement already satisfied: scipy>=1.0.0 in c:\users\ghg\miniconda3\lib\site-packages (from category_encoders) (1.11.3)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.1-cp311-cp311-win_amd64.whl (9.9 MB)
                                              0.0/9.9 MB ? eta -:--:--
                                              0.1/9.9 MB 2.3 MB/s eta 0:00:05
                                              0.1/9.9 MB 1.8 MB/s eta 0:00:06
                                              0.1/9.9 MB 819.2 kB/s eta 0:00:12
                                              0.2/9.9 MB 1.2 MB/s eta 0:00:09
                                              0.2/9.9 MB 1.1 MB/s eta 0:00:09
                                              0.2/9.9 MB 888.8 kB/s eta 0:00:11
     -                                        0.3/9.9 MB 1.1 MB/s eta 0:00:10
     -                                        0.5/9.9 MB 1.4 MB/s eta 0:00:07
     -                                        0.5/9.9 MB 1.4 MB/s eta 0:00:07
     --                                       0.6/9.9 MB 1.3 MB/s eta 0:00:07
     ----                                     1.0/9.9 MB 2.1 MB/s eta 0:00:05
     ----                                     1.0/9.9 MB 2.1 MB/s eta 0:00:05
     -----                                    1.3/9.9 MB 2.2 MB/s eta 0:00:04
     ------                                   1.6/9.9 MB 2.6 MB/s eta 0:00:04
     --------                                 2.2/9.9 MB 3.2 MB/s eta 0:00:03
     --------                                 2.2/9.9 MB 3.3 MB/s eta 0:00:03
     --------                                 2.2/9.9 MB 3.3 MB/s eta 0:00:03
     --------                                 2.2/9.9 MB 3.3 MB/s eta 0:00:03
     ------------                             3.0/9.9 MB 3.6 MB/s eta 0:00:02
     ------------                             3.0/9.9 MB 3.6 MB/s eta 0:00:02
     ---------------                          3.7/9.9 MB 3.9 MB/s eta 0:00:02
     ----------------                         4.1/9.9 MB 4.2 MB/s eta 0:00:02
     -----------------                        4.4/9.9 MB 4.3 MB/s eta 0:00:02
     -----------------                        4.4/9.9 MB 4.3 MB/s eta 0:00:02
     -----------------                        4.4/9.9 MB 4.3 MB/s eta 0:00:02
     ---------------------                    5.4/9.9 MB 4.6 MB/s eta 0:00:01
     -----------------------------            7.3/9.9 MB 6.0 MB/s eta 0:00:01
     -------------------------------          7.6/9.9 MB 6.0 MB/s eta 0:00:01
     ---------------------------------        8.1/9.9 MB 6.2 MB/s eta 0:00:01
     ----------------------------------       8.6/9.9 MB 6.3 MB/s eta 0:00:01
     -----------------------------------      8.8/9.9 MB 6.3 MB/s eta 0:00:01
     ------------------------------------     9.1/9.9 MB 6.3 MB/s eta 0:00:01
     --------------------------------------   9.6/9.9 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------  9.9/9.9 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------  9.9/9.9 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------  9.9/9.9 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------- 9.9/9.9 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.0.5 in c:\users\ghg\miniconda3\lib\site-packages (from category_encoders) (2.1.1)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-0.5.4-py2.py3-none-any.whl (233 kB)
                                              0.0/233.9 kB ? eta -:--:--
     -------------------------------------- 233.9/233.9 kB 7.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ghg\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ghg\miniconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ghg\miniconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\ghg\appdata\roaming\python\python311\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Collecting joblib>=1.1.1 (from scikit-learn>=0.20.0->category_encoders)
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.20.0->category_encoders)
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\ghg\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Installing collected packages: threadpoolctl, patsy, joblib, scikit-learn, statsmodels, category_encoders
Successfully installed category_encoders-2.6.3 joblib-1.3.2 patsy-0.5.4 scikit-learn-1.3.2 statsmodels-0.14.1 threadpoolctl-3.2.0

In [19]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
pip install category_encoders

Collecting category_encoders
  Obtaining dependency information for category_encoders from https://files.pythonhosted.org/packages/7f/e5/79a62e5c9c9ddbfa9ff5222240d408c1eeea4e38741a0dc8343edc7ef1ec/category_encoders-2.6.3-py2.py3-none-any.whl.metadata
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.26.0)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.3.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.11.4)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Obtaining dependency information for statsmodels>=0.9.0 from https://files.pythonhosted.org/packages/9a/b2/13833f94076dcc2709137fee92157ef5a0099a11ddff4f4b7cb301b35357/statsmodels-0.14.1-cp311-cp311-win_amd64.whl.metadata
  Downloading statsmodels-0.14.1-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: pandas>=1.0.5 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.1.1)
Collecting patsy>=0.5.1 (from category_encoders)
  Obtaining dependency information for patsy>=0.5.1 from https://files.pythonhosted.org/packages/29/ab/373449d6f741732f94e2d15d116a90f050b2857cb727b26d2f7bead50815/patsy-0.5.4-py2.py3-none-any.whl.metadata
  Downloading patsy-0.5.4-py2.py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ghg\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\ghg\appdata\roaming\python\python311\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ghg\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\ghg\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Using cached category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
Using cached patsy-0.5.4-py2.py3-none-any.whl (233 kB)
Using cached statsmodels-0.14.1-cp311-cp311-win_amd64.whl (9.9 MB)
Installing collected packages: patsy, statsmodels, category_encoders
Successfully installed category_encoders-2.6.3 patsy-0.5.4 statsmodels-0.14.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:

from category_encoders import BinaryEncoder
binary_encoder = BinaryEncoder()
df_binary = binary_encoder.fit_transform(df['day']) 
df_binary.head()

   day_0  day_1  day_2
0      0      0      1
1      0      0      1
2      0      0      1
3      0      0      1
4      0      0      1

In [23]:
# use pandas for feature encoding

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
# use pandas get dummies

get_dummies = pd.get_dummies(df, columns=['day'], drop_first=True)
get_dummies.head()

   total_bill   tip     sex smoker    time  size  day_Fri  day_Sat  day_Sun
0       16.99  1.01  Female     No  Dinner     2    False    False     True
1       10.34  1.66    Male     No  Dinner     3    False    False     True
2       21.01  3.50    Male     No  Dinner     3    False    False     True
3       23.68  3.31    Male     No  Dinner     2    False    False     True
4       24.59  3.61  Female     No  Dinner     4    False    False     True